### ISSUE TITLE
error on starting caves of qud

### ISSUE THREAD

**Issue by Hellcommander** [HeladoDeBrownie/Caves-of-Qud-Antiweight-Orbs#2]
Telemetry error: /Event/WriteTelemetryEvents: Invalid input parameters
Events[0].CustomTags: CustomTags item value Aetheric Beacon:unknown version;helado_AntiweightOrbs:1.0.0;Appearance Change Wish:unknown version;Astral Kitty:unknown version;Auto Disassemble Rifles:unknown version;AutoDisassemble Missiles:unknown version;Basil the Friendly Basilisk:unknown version;BetterTime:1.0;helado_BrewedBeverages:1.0.1;Camouflage:unknown version;Cat's Guns:unknown version;Clactobelle Pet:unknown version;Clever Girl:unknown version;Discretionary Valor:unknown version;Explorer Subtype:unknown version;Flammable Fungi:unknown version;Flammable Gas Generation:unknown version;Free Jungle Movement:unknown version;Gender and Pronoun Sets:unknown version;Heartbreak:unknown version;Hearthpyre:2.0.4;Heavy Weapons:unknown version;Improved Archery:unknown version;Improved Bionics:unknown version;Inaccurate at Moderate Range:unknown version;Injector Applicator Skill:unknown version;Legendary Crafter Boosts:unknown version;Limber:unknown version;Mangrove Visibility:unknown version;More Fluid Storage:unknown version;More mental mutations:unknown version;More Modifiers:unknown version;NoMoreAwfulDirections:unknown version;Over the Grey Mountains:unknown version;Pick Up Vases:unknown version;Playable Mopango:unknown version;Polearms:unknown version;Promethia's Playable Girshkin:unknown version;PsiTech:unknown version;Qud Fishing:unknown version;Qudllorful Pigments:unknown version;QudUX:2.0;Recoverable Item Mod Bits:unknown version;Recur:1.1.5;Rise of the ATU - Playable Androids:unknown version;Scaling Nightvision:unknown version;Sharpie:unknown version;Show Owner & Faction (in overlay tooltip):unknown version;SofterCleaveSound:1.0;Sparkle:1.0;SuppressScavengingPopups:1.0;Symbiotic Organisms: "Rendered" 2020 Update:unknown version;Telekinesis:unknown version;The Tenfold Path:unknown version;Unencumbered:1.1.0;WakeUp:1.0;Waldopacks:unknown version;WM Extended Mutations:unknown version;YouSeeACaveSpider:1.0.0;Your Own Personal Relics:unknown version; length 1939 exceeds limit of 128 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

System.NullReferenceException: Object reference not set to an instance of an object
  at ConsoleLib.Console.Keyboard+MouseEvent.CopyFrom (ConsoleLib.Console.Keyboard+MouseEvent source) [0x00000] in <5499b9c6f25744f696d04abce7e84aa5>:0 
  at ConsoleLib.Console.Keyboard.GetNextKey (System.Boolean MapDirectionsToArrows, System.Boolean pumpActions, System.Boolean waitForNext) [0x0003c] in <5499b9c6f25744f696d04abce7e84aa5>:0 
  at ConsoleLib.Console.Keyboard.getvk (System.Boolean MapDirectionToArrows, System.Boolean pumpActions, System.Boolean wait) [0x00000] in <5499b9c6f25744f696d04abce7e84aa5>:0 
  at XRL.Core.XRLCore._Start () [0x005d0] in <5499b9c6f25744f696d04abce7e84aa5>:0 
  at XRL.Core.XRLCore._ThreadStart () [0x0000a] in <5499b9c6f25744f696d04abce7e84aa5>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

disabling the antiweight orbs lets the game not crash on start

**Comment by HeladoDeBrownie** [comment]
unable to reproduce on either stable or beta, and the error doesn't look like it's coming from this mod. feel free to comment if you're able to provide more information, such as the smallest subset of all of your installed mods for which the error still occurs

**Comment by HeladoDeBrownie** [comment]
@Hellcommander i talked with gnarf (one of the devs) who seems to think it's a bug with the game itself and having too many mods installed. it has been seen now so you should just need to wait for it to be fixed and in the meantime use fewer mods
